version: '3.9'
services:

  db:
    image: postgres
    volumes:
      - postgres_value:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - ./.env
  migrations:
    build:
      dockerfile: build/migrations/Dockerfile
    container_name: goose_migrations
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      db:
        condition: service_healthy
  web:
    build:
      dockerfile: build/app/Dockerfile
    restart: on-failure
    depends_on:
      - db
      - migrations
    ports:
      - "3000:3000"
    env_file:
      - ./.env

volumes:
  postgres_value: